### ISSUE TITLE
Clean install fails because lack of 'dist' folder

### ISSUE THREAD

**Issue by sarimarton** [siassaj/cyclic-visualizer#1]
The Clone & Build section (https://github.com/siassaj/cyclic-visualizer#clone--build) of the intro page leads to an install error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 64
npm ERR! cyclic-visualizer@0.0.1 copyAssets: `cp -r assets/* dist/`
npm ERR! Exit status 64
```

The problem is that the 'dist' folder is not present at this time.

**Comment by siassaj** [comment]
thanks for catching it, i'll fix it up soon
